### ISSUE TITLE
Technical/simple view display

### ISSUE THREAD

**Issue by jadedjester** [LegoStormtroopr/aristotle-metadata-registry#14]
Suggest displaying all populated fields in the technical view, and a reduced number of fields in the simple view. This applies to all item types

E.g. Advanced view shows more than just the title and definition have been populated for the item. However, both view options only display the name and definition.

![advanced editor view](https://cloud.githubusercontent.com/assets/7429044/4430820/9694ed3c-4647-11e4-9d58-08903069e460.jpg)

Simple and technical view display the same content. 
http://aristotle.pythonanywhere.com/item/29?view=technical 
http://aristotle.pythonanywhere.com/item/29?view=simple

**Comment by LegoStormtroopr** [comment]
Closed as per discussion.
