### ISSUE TITLE
Unable to add images from PC

### ISSUE THREAD

**Issue by jadedjester** [LegoStormtroopr/aristotle-metadata-registry#54]
I'm able to add images from the internet without issue, however loading images from my personal computer fails. The editor inserts box where I've tried to add my image, but the image is not displayed. 

![adding_image_fail](https://cloud.githubusercontent.com/assets/7429044/4431890/d90c9e78-467c-11e4-8bea-44a6b351caa8.jpg)

**Comment by LegoStormtroopr** [comment]
This was rolled in with the editor updated and can be merged in to master soon.
