### ISSUE TITLE
Glossary items

### ISSUE THREAD

**Issue by jadedjester** [LegoStormtroopr/aristotle-metadata-registry#72]
The Glossary function needs a few updates.

1. When adding a glossary item the pop up box appears with a drop down list of possible glossary terms. This list will become very long, very quickly. There needs to be a better browser mechanism, and also a search function to reduce results based on specific criteria.
![glossary_insertpopup](https://cloud.githubusercontent.com/assets/7429044/4502606/50b04780-4aca-11e4-902c-e40779bbdaf4.jpg)

2. When adding the glossary term to text via the inline editor, the selected term is placed directly into the text. It would be helpful to have the option to (1) insert the term (as it works currently) and also the option to (2) link a term to selected text (hyperlink). The latter option is the how other comparable products operate. My automatic response was to try and highlight text to link, and said text was overwritten by the glossary being inserted. Could the glossary be smart enough to know whether you've highlighted text and auto default to the second option? Asking too much?
![glossary_inline_edits](https://cloud.githubusercontent.com/assets/7429044/4502596/33bf82e4-4aca-11e4-9875-b5601b8dc27a.jpg)

**Comment by LegoStormtroopr** [comment]
All fixed an closed with the new editor in #138
