### ISSUE TITLE
References to satisfy creative commons

### ISSUE THREAD

**Issue by jadedjester** [LegoStormtroopr/aristotle-metadata-registry#84]
I think we need an epic References section, and have got agreement from the brains trust.

Essentially, some header along the lines of References.. Then add space for Origin, recognised ID, URL, relevant documents etc.

Lets say we're referencing a standard from Standards Australia we can say Name of object according to their standard, the URL for the original documentation, File of the standard (if applicable), SA's ID of standard.

Same goes for content transferred from other systems, such as M. You could have name of object, M #ID, M's URL etc. It allows us to be upfront about the origins of content, honour the creative commons requirements by attributing ownership to the relevant party, and it sets the scene for whole of government standards sharing whilst helping reduce the impact of the inevitable silo effect.

Thoughts?

**Comment by LegoStormtroopr** [comment]
Closing this, as there hasn't been any rationale for it. Definitions and comments can include links, and there is an 'originURI' for content duplicated across systems.
